package cux.oracle.apps.pa.docnum.lov.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DocNumLovAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public DocNumLovAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) { /* package name */
        /* Configuration Name */launchTester("cux.oracle.apps.pa.docnum.lov.server", 
                                             "DocNumLovAMLocal");
    }

    /**Container's getter for ProjectVO1
     */
    public ProjectVOImpl getProjectVO1() {
        return (ProjectVOImpl)findViewObject("ProjectVO1");
    }
}
