package cux.oracle.apps.pa.pmp.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AMEActionHistoryVORowImpl extends OAViewRowImpl {
    public static final int WFITEMKEY = 0;
    public static final int TRANSACTIONTYPE = 1;
    public static final int TRANSACTIONID = 2;
    public static final int TRANSACTIONNUMBER = 3;
    public static final int SEQNUM = 4;
    public static final int APPRDESC = 5;
    public static final int EMPID = 6;
    public static final int EMPNAME = 7;
    public static final int USERNAME = 8;
    public static final int ACTION = 9;
    public static final int ACTIONDATE = 10;
    public static final int CREATEDBY = 11;
    public static final int CREATIONDATE = 12;
    public static final int LASTUPDATEDBY = 13;
    public static final int LASTUPDATEDATE = 14;
    public static final int LASTUPDATELOGIN = 15;
    public static final int NOTE = 16;
    public static final int SIGNFLAG = 17;
    public static final int IFHISTORYDATA = 18;
    public static final int IFAPPROVED = 19;

    /**This is the default constructor (do not remove)
     */
    public AMEActionHistoryVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute WfItemkey
     */
    public String getWfItemkey() {
        return (String)getAttributeInternal(WFITEMKEY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute WfItemkey
     */
    public void setWfItemkey(String value) {
        setAttributeInternal(WFITEMKEY, value);
    }

    /**Gets the attribute value for the calculated attribute TransactionType
     */
    public String getTransactionType() {
        return (String)getAttributeInternal(TRANSACTIONTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TransactionType
     */
    public void setTransactionType(String value) {
        setAttributeInternal(TRANSACTIONTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute TransactionId
     */
    public String getTransactionId() {
        return (String)getAttributeInternal(TRANSACTIONID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TransactionId
     */
    public void setTransactionId(String value) {
        setAttributeInternal(TRANSACTIONID, value);
    }

    /**Gets the attribute value for the calculated attribute TransactionNumber
     */
    public String getTransactionNumber() {
        return (String)getAttributeInternal(TRANSACTIONNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TransactionNumber
     */
    public void setTransactionNumber(String value) {
        setAttributeInternal(TRANSACTIONNUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute SeqNum
     */
    public Number getSeqNum() {
        return (Number)getAttributeInternal(SEQNUM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SeqNum
     */
    public void setSeqNum(Number value) {
        setAttributeInternal(SEQNUM, value);
    }

    /**Gets the attribute value for the calculated attribute ApprDesc
     */
    public String getApprDesc() {
        return (String)getAttributeInternal(APPRDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ApprDesc
     */
    public void setApprDesc(String value) {
        setAttributeInternal(APPRDESC, value);
    }

    /**Gets the attribute value for the calculated attribute EmpId
     */
    public Number getEmpId() {
        return (Number)getAttributeInternal(EMPID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmpId
     */
    public void setEmpId(Number value) {
        setAttributeInternal(EMPID, value);
    }

    /**Gets the attribute value for the calculated attribute EmpName
     */
    public String getEmpName() {
        return (String)getAttributeInternal(EMPNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmpName
     */
    public void setEmpName(String value) {
        setAttributeInternal(EMPNAME, value);
    }

    /**Gets the attribute value for the calculated attribute UserName
     */
    public String getUserName() {
        return (String)getAttributeInternal(USERNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute UserName
     */
    public void setUserName(String value) {
        setAttributeInternal(USERNAME, value);
    }


    /**Gets the attribute value for the calculated attribute ActionDate
     */
    public Date getActionDate() {
        return (Date)getAttributeInternal(ACTIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ActionDate
     */
    public void setActionDate(Date value) {
        setAttributeInternal(ACTIONDATE, value);
    }

    /**Gets the attribute value for the calculated attribute CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for the calculated attribute Note
     */
    public String getNote() {
        return (String)getAttributeInternal(NOTE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Note
     */
    public void setNote(String value) {
        setAttributeInternal(NOTE, value);
    }

    /**Gets the attribute value for the calculated attribute SignFlag
     */
    public String getSignFlag() {
        return (String)getAttributeInternal(SIGNFLAG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SignFlag
     */
    public void setSignFlag(String value) {
        setAttributeInternal(SIGNFLAG, value);
    }

    /**Gets the attribute value for the calculated attribute IfHistoryData
     */
    public String getIfHistoryData() {
        return (String)getAttributeInternal(IFHISTORYDATA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IfHistoryData
     */
    public void setIfHistoryData(String value) {
        setAttributeInternal(IFHISTORYDATA, value);
    }

    /**Gets the attribute value for the calculated attribute IfApproved
     */
    public String getIfApproved() {
        return (String)getAttributeInternal(IFAPPROVED);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IfApproved
     */
    public void setIfApproved(String value) {
        setAttributeInternal(IFAPPROVED, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case WFITEMKEY:
            return getWfItemkey();
        case TRANSACTIONTYPE:
            return getTransactionType();
        case TRANSACTIONID:
            return getTransactionId();
        case TRANSACTIONNUMBER:
            return getTransactionNumber();
        case SEQNUM:
            return getSeqNum();
        case APPRDESC:
            return getApprDesc();
        case EMPID:
            return getEmpId();
        case EMPNAME:
            return getEmpName();
        case USERNAME:
            return getUserName();
        case ACTION:
            return getAction();
        case ACTIONDATE:
            return getActionDate();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case NOTE:
            return getNote();
        case SIGNFLAG:
            return getSignFlag();
        case IFHISTORYDATA:
            return getIfHistoryData();
        case IFAPPROVED:
            return getIfApproved();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case WFITEMKEY:
            setWfItemkey((String)value);
            return;
        case TRANSACTIONTYPE:
            setTransactionType((String)value);
            return;
        case TRANSACTIONID:
            setTransactionId((String)value);
            return;
        case TRANSACTIONNUMBER:
            setTransactionNumber((String)value);
            return;
        case SEQNUM:
            setSeqNum((Number)value);
            return;
        case APPRDESC:
            setApprDesc((String)value);
            return;
        case EMPID:
            setEmpId((Number)value);
            return;
        case EMPNAME:
            setEmpName((String)value);
            return;
        case USERNAME:
            setUserName((String)value);
            return;
        case ACTION:
            setAction((String)value);
            return;
        case ACTIONDATE:
            setActionDate((Date)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case NOTE:
            setNote((String)value);
            return;
        case SIGNFLAG:
            setSignFlag((String)value);
            return;
        case IFHISTORYDATA:
            setIfHistoryData((String)value);
            return;
        case IFAPPROVED:
            setIfApproved((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute Action
     */
    public String getAction() {
        return (String)getAttributeInternal(ACTION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Action
     */
    public void setAction(String value) {
        setAttributeInternal(ACTION, value);
    }
}
