package cux.oracle.apps.per.bonus.specialawards.server;

import oracle.apps.fnd.framework.OAViewObject;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CuxSpecialAwardsDetailsAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public CuxSpecialAwardsDetailsAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) { /* package name */
        /* Configuration Name */launchTester("cux.oracle.apps.per.bonus.specialawards.server", 
                                             "CuxSpecialAwardsDetailsAMLocal");
    }

    /**Container's getter for CuxSpecialAwardsDetailsVO1
     */
    public CuxSpecialAwardsDetailsVOImpl getCuxSpecialAwardsDetailsVO1() {
        return (CuxSpecialAwardsDetailsVOImpl)findViewObject("CuxSpecialAwardsDetailsVO1");
    }

    public void execQuery(String lotId, String typeName) {
        /* 37 */OAViewObject vo = null;
        /* 38 */vo = (OAViewObject)getCuxSpecialAwardsDetailsVO1();
        /*    */
        /* 40 */String whereClause = 
            "LOT_ID =  '" + lotId + "' and TYPE_NAME = '" + typeName + "'";
        /*    */
        /* 42 */vo.setWhereClause(null);
        /* 43 */vo.setWhereClause(whereClause);
        /* 44 */vo.executeQuery();
        /*    */
    }
}
