package cux.oracle.apps.ap.oie.workflow.apexp.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CuxProBudgetVORowImpl extends OAViewRowImpl {
    public static final int BGTBIGNAME = 0;
    public static final int BGTBIGVALUE = 1;
    public static final int BGTBIGUSEDAMT = 2;
    public static final int BGTBIGUSEDPERCENT = 3;
    public static final int BGTBIGAVLAMT = 4;
    public static final int APPLYAMOUNT = 5;
    public static final int BGTBIGMTAMOUNT = 6;
    public static final int BGTBIGMTAMOUNTPERCENT = 7;
    public static final int PROBUDGETAMT = 8;
    public static final int PROUSEDAMT = 9;
    public static final int PROUSEDPERCENT = 10;
    public static final int PROAVLAMT = 11;
    public static final int PROMTAMOUNT = 12;
    public static final int PROMTAMOUNTPERCENT = 13;

    /**This is the default constructor (do not remove)
     */
    public CuxProBudgetVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute BgtBigName
     */
    public String getBgtBigName() {
        return (String)getAttributeInternal(BGTBIGNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BgtBigName
     */
    public void setBgtBigName(String value) {
        setAttributeInternal(BGTBIGNAME, value);
    }

    /**Gets the attribute value for the calculated attribute BgtBigValue
     */
    public Number getBgtBigValue() {
        return (Number)getAttributeInternal(BGTBIGVALUE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BgtBigValue
     */
    public void setBgtBigValue(Number value) {
        setAttributeInternal(BGTBIGVALUE, value);
    }

    /**Gets the attribute value for the calculated attribute BgtBigUsedAmt
     */
    public Number getBgtBigUsedAmt() {
        return (Number)getAttributeInternal(BGTBIGUSEDAMT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BgtBigUsedAmt
     */
    public void setBgtBigUsedAmt(Number value) {
        setAttributeInternal(BGTBIGUSEDAMT, value);
    }

    /**Gets the attribute value for the calculated attribute BgtBigUsedPercent
     */
    public Number getBgtBigUsedPercent() {
        return (Number)getAttributeInternal(BGTBIGUSEDPERCENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BgtBigUsedPercent
     */
    public void setBgtBigUsedPercent(Number value) {
        setAttributeInternal(BGTBIGUSEDPERCENT, value);
    }

    /**Gets the attribute value for the calculated attribute BgtBigAvlAmt
     */
    public Number getBgtBigAvlAmt() {
        return (Number)getAttributeInternal(BGTBIGAVLAMT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BgtBigAvlAmt
     */
    public void setBgtBigAvlAmt(Number value) {
        setAttributeInternal(BGTBIGAVLAMT, value);
    }

    /**Gets the attribute value for the calculated attribute ApplyAmount
     */
    public Number getApplyAmount() {
        return (Number)getAttributeInternal(APPLYAMOUNT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ApplyAmount
     */
    public void setApplyAmount(Number value) {
        setAttributeInternal(APPLYAMOUNT, value);
    }

    /**Gets the attribute value for the calculated attribute BgtBigMtAmount
     */
    public Number getBgtBigMtAmount() {
        return (Number)getAttributeInternal(BGTBIGMTAMOUNT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BgtBigMtAmount
     */
    public void setBgtBigMtAmount(Number value) {
        setAttributeInternal(BGTBIGMTAMOUNT, value);
    }

    /**Gets the attribute value for the calculated attribute BgtBigMtAmountPercent
     */
    public Number getBgtBigMtAmountPercent() {
        return (Number)getAttributeInternal(BGTBIGMTAMOUNTPERCENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BgtBigMtAmountPercent
     */
    public void setBgtBigMtAmountPercent(Number value) {
        setAttributeInternal(BGTBIGMTAMOUNTPERCENT, value);
    }

    /**Gets the attribute value for the calculated attribute ProBudgetAmt
     */
    public Number getProBudgetAmt() {
        return (Number)getAttributeInternal(PROBUDGETAMT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProBudgetAmt
     */
    public void setProBudgetAmt(Number value) {
        setAttributeInternal(PROBUDGETAMT, value);
    }

    /**Gets the attribute value for the calculated attribute ProUsedAmt
     */
    public Number getProUsedAmt() {
        return (Number)getAttributeInternal(PROUSEDAMT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProUsedAmt
     */
    public void setProUsedAmt(Number value) {
        setAttributeInternal(PROUSEDAMT, value);
    }

    /**Gets the attribute value for the calculated attribute ProUsedPercent
     */
    public Number getProUsedPercent() {
        return (Number)getAttributeInternal(PROUSEDPERCENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProUsedPercent
     */
    public void setProUsedPercent(Number value) {
        setAttributeInternal(PROUSEDPERCENT, value);
    }

    /**Gets the attribute value for the calculated attribute ProAvlAmt
     */
    public Number getProAvlAmt() {
        return (Number)getAttributeInternal(PROAVLAMT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProAvlAmt
     */
    public void setProAvlAmt(Number value) {
        setAttributeInternal(PROAVLAMT, value);
    }

    /**Gets the attribute value for the calculated attribute ProMtAmount
     */
    public Number getProMtAmount() {
        return (Number)getAttributeInternal(PROMTAMOUNT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProMtAmount
     */
    public void setProMtAmount(Number value) {
        setAttributeInternal(PROMTAMOUNT, value);
    }

    /**Gets the attribute value for the calculated attribute ProMtAmountPercent
     */
    public Number getProMtAmountPercent() {
        return (Number)getAttributeInternal(PROMTAMOUNTPERCENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProMtAmountPercent
     */
    public void setProMtAmountPercent(Number value) {
        setAttributeInternal(PROMTAMOUNTPERCENT, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case BGTBIGNAME:
            return getBgtBigName();
        case BGTBIGVALUE:
            return getBgtBigValue();
        case BGTBIGUSEDAMT:
            return getBgtBigUsedAmt();
        case BGTBIGUSEDPERCENT:
            return getBgtBigUsedPercent();
        case BGTBIGAVLAMT:
            return getBgtBigAvlAmt();
        case APPLYAMOUNT:
            return getApplyAmount();
        case BGTBIGMTAMOUNT:
            return getBgtBigMtAmount();
        case BGTBIGMTAMOUNTPERCENT:
            return getBgtBigMtAmountPercent();
        case PROBUDGETAMT:
            return getProBudgetAmt();
        case PROUSEDAMT:
            return getProUsedAmt();
        case PROUSEDPERCENT:
            return getProUsedPercent();
        case PROAVLAMT:
            return getProAvlAmt();
        case PROMTAMOUNT:
            return getProMtAmount();
        case PROMTAMOUNTPERCENT:
            return getProMtAmountPercent();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case BGTBIGNAME:
            setBgtBigName((String)value);
            return;
        case BGTBIGVALUE:
            setBgtBigValue((Number)value);
            return;
        case BGTBIGUSEDAMT:
            setBgtBigUsedAmt((Number)value);
            return;
        case BGTBIGUSEDPERCENT:
            setBgtBigUsedPercent((Number)value);
            return;
        case BGTBIGAVLAMT:
            setBgtBigAvlAmt((Number)value);
            return;
        case APPLYAMOUNT:
            setApplyAmount((Number)value);
            return;
        case BGTBIGMTAMOUNT:
            setBgtBigMtAmount((Number)value);
            return;
        case BGTBIGMTAMOUNTPERCENT:
            setBgtBigMtAmountPercent((Number)value);
            return;
        case PROBUDGETAMT:
            setProBudgetAmt((Number)value);
            return;
        case PROUSEDAMT:
            setProUsedAmt((Number)value);
            return;
        case PROUSEDPERCENT:
            setProUsedPercent((Number)value);
            return;
        case PROAVLAMT:
            setProAvlAmt((Number)value);
            return;
        case PROMTAMOUNT:
            setProMtAmount((Number)value);
            return;
        case PROMTAMOUNTPERCENT:
            setProMtAmountPercent((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
