package cux.oracle.apps.per.bonus.advanceawards.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AdvAwardsSummaryOfficeVORowImpl extends OAViewRowImpl {
    public static final int EMPLOYEENUMBER = 0;
    public static final int LASTNAME = 1;
    public static final int DEPNAME = 2;
    public static final int DECMONTHBONUS = 3;
    public static final int DECDEPTBONUS = 4;
    public static final int DECYEARBONUS = 5;
    public static final int DECDIST = 6;
    public static final int ORGNAME = 7;
    public static final int ROWSEQ = 8;

    /**This is the default constructor (do not remove)
     */
    public AdvAwardsSummaryOfficeVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute EmployeeNumber
     */
    public String getEmployeeNumber() {
        return (String)getAttributeInternal(EMPLOYEENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmployeeNumber
     */
    public void setEmployeeNumber(String value) {
        setAttributeInternal(EMPLOYEENUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute LastName
     */
    public String getLastName() {
        return (String)getAttributeInternal(LASTNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastName
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**Gets the attribute value for the calculated attribute DepName
     */
    public String getDepName() {
        return (String)getAttributeInternal(DEPNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DepName
     */
    public void setDepName(String value) {
        setAttributeInternal(DEPNAME, value);
    }

    /**Gets the attribute value for the calculated attribute DecMonthBonus
     */
    public String getDecMonthBonus() {
        return (String)getAttributeInternal(DECMONTHBONUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DecMonthBonus
     */
    public void setDecMonthBonus(String value) {
        setAttributeInternal(DECMONTHBONUS, value);
    }

    /**Gets the attribute value for the calculated attribute DecDeptBonus
     */
    public String getDecDeptBonus() {
        return (String)getAttributeInternal(DECDEPTBONUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DecDeptBonus
     */
    public void setDecDeptBonus(String value) {
        setAttributeInternal(DECDEPTBONUS, value);
    }

    /**Gets the attribute value for the calculated attribute DecYearBonus
     */
    public String getDecYearBonus() {
        return (String)getAttributeInternal(DECYEARBONUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DecYearBonus
     */
    public void setDecYearBonus(String value) {
        setAttributeInternal(DECYEARBONUS, value);
    }

    /**Gets the attribute value for the calculated attribute DecDist
     */
    public String getDecDist() {
        return (String)getAttributeInternal(DECDIST);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DecDist
     */
    public void setDecDist(String value) {
        setAttributeInternal(DECDIST, value);
    }

    /**Gets the attribute value for the calculated attribute Orgname
     */
    public String getOrgname() {
        return (String)getAttributeInternal(ORGNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Orgname
     */
    public void setOrgname(String value) {
        setAttributeInternal(ORGNAME, value);
    }

    /**Gets the attribute value for the calculated attribute RowSeq
     */
    public Number getRowSeq() {
        return (Number)getAttributeInternal(ROWSEQ);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RowSeq
     */
    public void setRowSeq(Number value) {
        setAttributeInternal(ROWSEQ, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EMPLOYEENUMBER:
            return getEmployeeNumber();
        case LASTNAME:
            return getLastName();
        case DEPNAME:
            return getDepName();
        case DECMONTHBONUS:
            return getDecMonthBonus();
        case DECDEPTBONUS:
            return getDecDeptBonus();
        case DECYEARBONUS:
            return getDecYearBonus();
        case DECDIST:
            return getDecDist();
        case ORGNAME:
            return getOrgname();
        case ROWSEQ:
            return getRowSeq();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EMPLOYEENUMBER:
            setEmployeeNumber((String)value);
            return;
        case LASTNAME:
            setLastName((String)value);
            return;
        case DEPNAME:
            setDepName((String)value);
            return;
        case DECMONTHBONUS:
            setDecMonthBonus((String)value);
            return;
        case DECDEPTBONUS:
            setDecDeptBonus((String)value);
            return;
        case DECYEARBONUS:
            setDecYearBonus((String)value);
            return;
        case DECDIST:
            setDecDist((String)value);
            return;
        case ORGNAME:
            setOrgname((String)value);
            return;
        case ROWSEQ:
            setRowSeq((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
