package cux.oracle.apps.per.bonus.advanceawards.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CuxBonusOfficePersonDistVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public CuxBonusOfficePersonDistVOImpl() {
    }

    public void initQuery(String bonusType, String distDate, int deptOrgID) {
        this.setWhereClauseParams(null);
        this.setWhereClause(null);
        this.setWhereClauseParams(new Object[] { new Integer(deptOrgID), 
                                                 bonusType, distDate });
    }
}
