package cux.oracle.apps.per.review.server.common;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class PerReviewGroupEOImplMsgBundle extends JboResourceBundle {

    static final Object[][] sMessageStrings = 
    { { "PerReviewGroupEO_Rule_0", "ͬһ��֯�¿�Ⱥ��������" } };

    /**This is the default constructor (do not remove)
     */
    public PerReviewGroupEOImplMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
