package cux.oracle.apps.per.poplist.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class KPIScoreMethodVORowImpl extends OAViewRowImpl {
    public static final int EPMSMCODE = 0;
    public static final int EPMSMNAME = 1;

    /**This is the default constructor (do not remove)
     */
    public KPIScoreMethodVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute EpmSmCode
     */
    public String getEpmSmCode() {
        return (String)getAttributeInternal(EPMSMCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EpmSmCode
     */
    public void setEpmSmCode(String value) {
        setAttributeInternal(EPMSMCODE, value);
    }

    /**Gets the attribute value for the calculated attribute EpmSmName
     */
    public String getEpmSmName() {
        return (String)getAttributeInternal(EPMSMNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EpmSmName
     */
    public void setEpmSmName(String value) {
        setAttributeInternal(EPMSMNAME, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EPMSMCODE:
            return getEpmSmCode();
        case EPMSMNAME:
            return getEpmSmName();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
