package cux.oracle.apps.po.deliver.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CuxPoSupEvlConfVORowImpl extends OAViewRowImpl {
    public static final int SEC = 0;
    public static final int VALUESEC = 1;
    public static final int RENDERFLAG = 2;
    public static final int REQUIREDFLAG = 3;

    /**This is the default constructor (do not remove)
     */
    public CuxPoSupEvlConfVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Sec
     */
    public String getSec() {
        return (String)getAttributeInternal(SEC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Sec
     */
    public void setSec(String value) {
        setAttributeInternal(SEC, value);
    }

    /**Gets the attribute value for the calculated attribute ValueSec
     */
    public String getValueSec() {
        return (String)getAttributeInternal(VALUESEC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ValueSec
     */
    public void setValueSec(String value) {
        setAttributeInternal(VALUESEC, value);
    }

    /**Gets the attribute value for the calculated attribute RenderFlag
     */
    public String getRenderFlag() {
        return (String)getAttributeInternal(RENDERFLAG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RenderFlag
     */
    public void setRenderFlag(String value) {
        setAttributeInternal(RENDERFLAG, value);
    }

    /**Gets the attribute value for the calculated attribute RequiredFlag
     */
    public String getRequiredFlag() {
        return (String)getAttributeInternal(REQUIREDFLAG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RequiredFlag
     */
    public void setRequiredFlag(String value) {
        setAttributeInternal(REQUIREDFLAG, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SEC:
            return getSec();
        case VALUESEC:
            return getValueSec();
        case RENDERFLAG:
            return getRenderFlag();
        case REQUIREDFLAG:
            return getRequiredFlag();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SEC:
            setSec((String)value);
            return;
        case VALUESEC:
            setValueSec((String)value);
            return;
        case RENDERFLAG:
            setRenderFlag((String)value);
            return;
        case REQUIREDFLAG:
            setRequiredFlag((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
