package cux.oracle.apps.po.deliver.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CuxPoSupEvlConfVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public CuxPoSupEvlConfVOImpl() {
    }

    /**
     * 
     * @param uniqSeq
     * @param attributeSeq
     */
    public void query(Number uniqSeq, int attributeSeq) {
        this.setWhereClause(null);
        this.setWhereClauseParams(null);
        this.setWhereClause("sec = :1 and value_sec=:2");
        this.setWhereClauseParams(new Object[] { uniqSeq, 
                                                 new Number(attributeSeq) });
        this.executeQuery();
    }
}
