package cux.oracle.apps.hxc.selfservice.timecard.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EnfiHxcAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public EnfiHxcAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) { /* package name */
        /* Configuration Name */launchTester("cux.oracle.apps.hxc.selfservice.timecard.server", 
                                             "EnfiHxcAMLocal");
    }


    /**Container's getter for CuxProjectVO
     */
    public ProjectVOImpl getCuxProjectVO() {
        return (ProjectVOImpl)findViewObject("CuxProjectVO");
    }

    /**Container's getter for CuxTaskVO
     */
    public TaskVOImpl getCuxTaskVO() {
        return (TaskVOImpl)findViewObject("CuxTaskVO");
    }
}
