package cux.oracle.apps.po.autocreate.lov.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CuxAutocreateLovAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public CuxAutocreateLovAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) { /* package name */
        /* Configuration Name */launchTester("cux.oracle.apps.po.autocreate.lov.server", 
                                             "CuxAutocreateLovAMLocal");
    }

    /**Container's getter for PoClassVO1
     */
    public PoClassVOImpl getPoClassVO1() {
        return (PoClassVOImpl)findViewObject("PoClassVO1");
    }

    /**Container's getter for PoPurTypeVO1
     */
    public PoPurTypeVOImpl getPoPurTypeVO1() {
        return (PoPurTypeVOImpl)findViewObject("PoPurTypeVO1");
    }

    /**Container's getter for PoHeaderVO1
     */
    public PoHeaderVOImpl getPoHeaderVO1() {
        return (PoHeaderVOImpl)findViewObject("PoHeaderVO1");
    }
}
