package cux.oracle.apps.per.review.server;

import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppraisalEOImpl extends OAEntityImpl {
    public static final int APPRAISALID = 0;
    public static final int ORGANIZATIONID = 1;
    public static final int APPRAISALPERSONID = 2;
    public static final int PROMISERPERSONID = 3;
    public static final int WFITEMKEY = 4;
    public static final int EFFECTIVEDATE = 5;
    public static final int SIGNDATE = 6;
    public static final int APPRAISALGROUPID = 7;
    public static final int PHASEID = 8;
    public static final int PERIODTYPEID = 9;
    public static final int APPRAISALYEAR = 10;
    public static final int PERIODID = 11;
    public static final int STATUSID = 12;
    public static final int ENABLED = 13;
    public static final int APPROVALNUM = 14;
    public static final int CALMARK = 15;
    public static final int ORIMARK = 16;
    public static final int MODMARK = 17;
    public static final int FINALMARK = 18;
    public static final int ORILEVEL = 19;
    public static final int FINALLEVEL = 20;
    public static final int ATTRIBUTECATEGORY = 21;
    public static final int ATTRIBUTE1 = 22;
    public static final int ATTRIBUTE2 = 23;
    public static final int ATTRIBUTE3 = 24;
    public static final int ATTRIBUTE4 = 25;
    public static final int ATTRIBUTE5 = 26;
    public static final int LASTUPDATEDATE = 27;
    public static final int LASTUPDATEDBY = 28;
    public static final int LASTUPDATELOGIN = 29;
    public static final int CREATEDBY = 30;
    public static final int CREATIONDATE = 31;
    public static final int APPRAISALDATE = 32;
    public static final int COMPANYID = 33;
    public static final int YEAR = 34;
    private static AppraisalEODefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public AppraisalEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (AppraisalEODefImpl)EntityDefImpl.findDefObject("cux.oracle.apps.per.review.server.AppraisalEO");
        }
        return mDefinitionObject;
    }

    /**Add attribute defaulting logic in this method.
     */
    public void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**Add Entity validation code in this method.
     */
    protected void validateEntity() {
        super.validateEntity();
    }

    /**Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**Custom DML update/insert/delete logic here.
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }

    /**Gets the attribute value for AppraisalId, using the alias name AppraisalId
     */
    public Number getAppraisalId() {
        return (Number)getAttributeInternal(APPRAISALID);
    }

    /**Sets <code>value</code> as the attribute value for AppraisalId
     */
    public void setAppraisalId(Number value) {
        setAttributeInternal(APPRAISALID, value);
    }

    /**Gets the attribute value for OrganizationId, using the alias name OrganizationId
     */
    public Number getOrganizationId() {
        return (Number)getAttributeInternal(ORGANIZATIONID);
    }

    /**Sets <code>value</code> as the attribute value for OrganizationId
     */
    public void setOrganizationId(Number value) {
        setAttributeInternal(ORGANIZATIONID, value);
    }

    /**Gets the attribute value for AppraisalPersonId, using the alias name AppraisalPersonId
     */
    public Number getAppraisalPersonId() {
        return (Number)getAttributeInternal(APPRAISALPERSONID);
    }

    /**Sets <code>value</code> as the attribute value for AppraisalPersonId
     */
    public void setAppraisalPersonId(Number value) {
        setAttributeInternal(APPRAISALPERSONID, value);
    }


    /**Gets the attribute value for PromiserPersonId, using the alias name PromiserPersonId
     */
    public Number getPromiserPersonId() {
        return (Number)getAttributeInternal(PROMISERPERSONID);
    }

    /**Sets <code>value</code> as the attribute value for PromiserPersonId
     */
    public void setPromiserPersonId(Number value) {
        setAttributeInternal(PROMISERPERSONID, value);
    }

    /**Gets the attribute value for WfItemKey, using the alias name WfItemKey
     */
    public String getWfItemKey() {
        return (String)getAttributeInternal(WFITEMKEY);
    }

    /**Sets <code>value</code> as the attribute value for WfItemKey
     */
    public void setWfItemKey(String value) {
        setAttributeInternal(WFITEMKEY, value);
    }


    /**Gets the attribute value for EffectiveDate, using the alias name EffectiveDate
     */
    public Date getEffectiveDate() {
        return (Date)getAttributeInternal(EFFECTIVEDATE);
    }

    /**Sets <code>value</code> as the attribute value for EffectiveDate
     */
    public void setEffectiveDate(Date value) {
        setAttributeInternal(EFFECTIVEDATE, value);
    }

    /**Gets the attribute value for SignDate, using the alias name SignDate
     */
    public Date getSignDate() {
        return (Date)getAttributeInternal(SIGNDATE);
    }

    /**Sets <code>value</code> as the attribute value for SignDate
     */
    public void setSignDate(Date value) {
        setAttributeInternal(SIGNDATE, value);
    }

    /**Gets the attribute value for AppraisalGroupId, using the alias name AppraisalGroupId
     */
    public String getAppraisalGroupId() {
        return (String)getAttributeInternal(APPRAISALGROUPID);
    }

    /**Sets <code>value</code> as the attribute value for AppraisalGroupId
     */
    public void setAppraisalGroupId(String value) {
        setAttributeInternal(APPRAISALGROUPID, value);
    }

    /**Gets the attribute value for PhaseId, using the alias name PhaseId
     */
    public String getPhaseId() {
        return (String)getAttributeInternal(PHASEID);
    }

    /**Sets <code>value</code> as the attribute value for PhaseId
     */
    public void setPhaseId(String value) {
        setAttributeInternal(PHASEID, value);
    }

    /**Gets the attribute value for PeriodTypeId, using the alias name PeriodTypeId
     */
    public String getPeriodTypeId() {
        return (String)getAttributeInternal(PERIODTYPEID);
    }

    /**Sets <code>value</code> as the attribute value for PeriodTypeId
     */
    public void setPeriodTypeId(String value) {
        setAttributeInternal(PERIODTYPEID, value);
    }

    /**Gets the attribute value for AppraisalYear, using the alias name AppraisalYear
     */
    public String getAppraisalYear() {
        return (String)getAttributeInternal(APPRAISALYEAR);
    }

    /**Sets <code>value</code> as the attribute value for AppraisalYear
     */
    public void setAppraisalYear(String value) {
        setAttributeInternal(APPRAISALYEAR, value);
    }

    /**Gets the attribute value for PeriodId, using the alias name PeriodId
     */
    public String getPeriodId() {
        return (String)getAttributeInternal(PERIODID);
    }

    /**Sets <code>value</code> as the attribute value for PeriodId
     */
    public void setPeriodId(String value) {
        setAttributeInternal(PERIODID, value);
    }

    /**Gets the attribute value for StatusId, using the alias name StatusId
     */
    public String getStatusId() {
        return (String)getAttributeInternal(STATUSID);
    }

    /**Sets <code>value</code> as the attribute value for StatusId
     */
    public void setStatusId(String value) {
        setAttributeInternal(STATUSID, value);
    }

    /**Gets the attribute value for Enabled, using the alias name Enabled
     */
    public String getEnabled() {
        return (String)getAttributeInternal(ENABLED);
    }

    /**Sets <code>value</code> as the attribute value for Enabled
     */
    public void setEnabled(String value) {
        setAttributeInternal(ENABLED, value);
    }

    /**Gets the attribute value for ApprovalNum, using the alias name ApprovalNum
     */
    public Number getApprovalNum() {
        return (Number)getAttributeInternal(APPROVALNUM);
    }

    /**Sets <code>value</code> as the attribute value for ApprovalNum
     */
    public void setApprovalNum(Number value) {
        setAttributeInternal(APPROVALNUM, value);
    }

    /**Gets the attribute value for CalMark, using the alias name CalMark
     */
    public Number getCalMark() {
        return (Number)getAttributeInternal(CALMARK);
    }

    /**Sets <code>value</code> as the attribute value for CalMark
     */
    public void setCalMark(Number value) {
        setAttributeInternal(CALMARK, value);
    }

    /**Gets the attribute value for OriMark, using the alias name OriMark
     */
    public Number getOriMark() {
        return (Number)getAttributeInternal(ORIMARK);
    }

    /**Sets <code>value</code> as the attribute value for OriMark
     */
    public void setOriMark(Number value) {
        setAttributeInternal(ORIMARK, value);
    }

    /**Gets the attribute value for ModMark, using the alias name ModMark
     */
    public Number getModMark() {
        return (Number)getAttributeInternal(MODMARK);
    }

    /**Sets <code>value</code> as the attribute value for ModMark
     */
    public void setModMark(Number value) {
        setAttributeInternal(MODMARK, value);
    }

    /**Gets the attribute value for FinalMark, using the alias name FinalMark
     */
    public Number getFinalMark() {
        return (Number)getAttributeInternal(FINALMARK);
    }

    /**Sets <code>value</code> as the attribute value for FinalMark
     */
    public void setFinalMark(Number value) {
        setAttributeInternal(FINALMARK, value);
    }

    /**Gets the attribute value for OriLevel, using the alias name OriLevel
     */
    public String getOriLevel() {
        return (String)getAttributeInternal(ORILEVEL);
    }

    /**Sets <code>value</code> as the attribute value for OriLevel
     */
    public void setOriLevel(String value) {
        setAttributeInternal(ORILEVEL, value);
    }

    /**Gets the attribute value for FinalLevel, using the alias name FinalLevel
     */
    public String getFinalLevel() {
        return (String)getAttributeInternal(FINALLEVEL);
    }

    /**Sets <code>value</code> as the attribute value for FinalLevel
     */
    public void setFinalLevel(String value) {
        setAttributeInternal(FINALLEVEL, value);
    }

    /**Gets the attribute value for AttributeCategory, using the alias name AttributeCategory
     */
    public String getAttributeCategory() {
        return (String)getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**Sets <code>value</code> as the attribute value for AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**Gets the attribute value for Attribute1, using the alias name Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for Attribute2, using the alias name Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for Attribute3, using the alias name Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for Attribute4, using the alias name Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for Attribute5, using the alias name Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case APPRAISALID:
            return getAppraisalId();
        case ORGANIZATIONID:
            return getOrganizationId();
        case APPRAISALPERSONID:
            return getAppraisalPersonId();
        case PROMISERPERSONID:
            return getPromiserPersonId();
        case WFITEMKEY:
            return getWfItemKey();
        case EFFECTIVEDATE:
            return getEffectiveDate();
        case SIGNDATE:
            return getSignDate();
        case APPRAISALGROUPID:
            return getAppraisalGroupId();
        case PHASEID:
            return getPhaseId();
        case PERIODTYPEID:
            return getPeriodTypeId();
        case APPRAISALYEAR:
            return getAppraisalYear();
        case PERIODID:
            return getPeriodId();
        case STATUSID:
            return getStatusId();
        case ENABLED:
            return getEnabled();
        case APPROVALNUM:
            return getApprovalNum();
        case CALMARK:
            return getCalMark();
        case ORIMARK:
            return getOriMark();
        case MODMARK:
            return getModMark();
        case FINALMARK:
            return getFinalMark();
        case ORILEVEL:
            return getOriLevel();
        case FINALLEVEL:
            return getFinalLevel();
        case ATTRIBUTECATEGORY:
            return getAttributeCategory();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case APPRAISALDATE:
            return getAppraisalDate();
        case COMPANYID:
            return getCompanyId();
        case YEAR:
            return getYear();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case APPRAISALID:
            setAppraisalId((Number)value);
            return;
        case ORGANIZATIONID:
            setOrganizationId((Number)value);
            return;
        case APPRAISALPERSONID:
            setAppraisalPersonId((Number)value);
            return;
        case PROMISERPERSONID:
            setPromiserPersonId((Number)value);
            return;
        case WFITEMKEY:
            setWfItemKey((String)value);
            return;
        case EFFECTIVEDATE:
            setEffectiveDate((Date)value);
            return;
        case SIGNDATE:
            setSignDate((Date)value);
            return;
        case APPRAISALGROUPID:
            setAppraisalGroupId((String)value);
            return;
        case PHASEID:
            setPhaseId((String)value);
            return;
        case PERIODTYPEID:
            setPeriodTypeId((String)value);
            return;
        case APPRAISALYEAR:
            setAppraisalYear((String)value);
            return;
        case PERIODID:
            setPeriodId((String)value);
            return;
        case STATUSID:
            setStatusId((String)value);
            return;
        case ENABLED:
            setEnabled((String)value);
            return;
        case APPROVALNUM:
            setApprovalNum((Number)value);
            return;
        case CALMARK:
            setCalMark((Number)value);
            return;
        case ORIMARK:
            setOriMark((Number)value);
            return;
        case MODMARK:
            setModMark((Number)value);
            return;
        case FINALMARK:
            setFinalMark((Number)value);
            return;
        case ORILEVEL:
            setOriLevel((String)value);
            return;
        case FINALLEVEL:
            setFinalLevel((String)value);
            return;
        case ATTRIBUTECATEGORY:
            setAttributeCategory((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case APPRAISALDATE:
            setAppraisalDate((Date)value);
            return;
        case COMPANYID:
            setCompanyId((Number)value);
            return;
        case YEAR:
            setYear((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for AppraisalDate, using the alias name AppraisalDate
     */
    public Date getAppraisalDate() {
        return (Date)getAttributeInternal(APPRAISALDATE);
    }

    /**Sets <code>value</code> as the attribute value for AppraisalDate
     */
    public void setAppraisalDate(Date value) {
        setAttributeInternal(APPRAISALDATE, value);
    }

    /**Gets the attribute value for CompanyId, using the alias name CompanyId
     */
    public Number getCompanyId() {
        return (Number)getAttributeInternal(COMPANYID);
    }

    /**Sets <code>value</code> as the attribute value for CompanyId
     */
    public void setCompanyId(Number value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**Gets the attribute value for Year, using the alias name Year
     */
    public String getYear() {
        return (String)getAttributeInternal(YEAR);
    }

    /**Sets <code>value</code> as the attribute value for Year
     */
    public void setYear(String value) {
        setAttributeInternal(YEAR, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number appraisalId) {
        return new Key(new Object[] { appraisalId });
    }
}
