package cux.oracle.apps.per.review.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReviewWorkflowVORowImpl extends OAViewRowImpl {

    public static final int ATTRIBUTE1 = 0;
    public static final int ATTRIBUTE2 = 1;
    public static final int ATTRIBUTE3 = 2;
    public static final int ATTRIBUTE4 = 3;
    public static final int ATTRIBUTE5 = 4;
    public static final int CREATEDBY = 5;
    public static final int CREATIONDATE = 6;
    public static final int EPMPERIODCODE = 7;
    public static final int EPMPHASECLASSCODE = 8;
    public static final int GROUPID = 9;
    public static final int ISATTENDED = 10;
    public static final int LASTUPDATEDBY = 11;
    public static final int LASTUPDATEDATE = 12;
    public static final int LASTUPDATELOGIN = 13;
    public static final int ORGID = 14;
    public static final int EPMWORKFLOWID = 15;

    /**This is the default constructor (do not remove)
     */
    public ReviewWorkflowVORowImpl() {
    }


    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case EPMPERIODCODE:
            return getEpmPeriodCode();
        case EPMPHASECLASSCODE:
            return getEpmPhaseClassCode();
        case GROUPID:
            return getGroupId();
        case ISATTENDED:
            return getIsAttended();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case ORGID:
            return getOrgId();
        case EPMWORKFLOWID:
            return getEpmWorkflowId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case EPMPERIODCODE:
            setEpmPeriodCode((String)value);
            return;
        case EPMPHASECLASSCODE:
            setEpmPhaseClassCode((String)value);
            return;
        case GROUPID:
            setGroupId((Number)value);
            return;
        case ISATTENDED:
            setIsAttended((String)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case ORGID:
            setOrgId((Number)value);
            return;
        case EPMWORKFLOWID:
            setEpmWorkflowId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets ReviewWorkflowEO entity object.
     */
    public ReviewWorkflowEOImpl getReviewWorkflowEO() {
        return (ReviewWorkflowEOImpl)getEntity(0);
    }

    /**Gets the attribute value for the calculated attribute Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**Gets the attribute value for the calculated attribute CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for the calculated attribute EpmPeriodCode
     */
    public String getEpmPeriodCode() {
        return (String)getAttributeInternal(EPMPERIODCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EpmPeriodCode
     */
    public void setEpmPeriodCode(String value) {
        setAttributeInternal(EPMPERIODCODE, value);
    }

    /**Gets the attribute value for the calculated attribute EpmPhaseClassCode
     */
    public String getEpmPhaseClassCode() {
        return (String)getAttributeInternal(EPMPHASECLASSCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EpmPhaseClassCode
     */
    public void setEpmPhaseClassCode(String value) {
        setAttributeInternal(EPMPHASECLASSCODE, value);
    }

    /**Gets the attribute value for the calculated attribute GroupId
     */
    public Number getGroupId() {
        return (Number)getAttributeInternal(GROUPID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute GroupId
     */
    public void setGroupId(Number value) {
        setAttributeInternal(GROUPID, value);
    }

    /**Gets the attribute value for the calculated attribute IsAttended
     */
    public String getIsAttended() {
        return (String)getAttributeInternal(ISATTENDED);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IsAttended
     */
    public void setIsAttended(String value) {
        setAttributeInternal(ISATTENDED, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for the calculated attribute OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**Gets the attribute value for the calculated attribute EpmWorkflowId
     */
    public Number getEpmWorkflowId() {
        return (Number)getAttributeInternal(EPMWORKFLOWID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EpmWorkflowId
     */
    public void setEpmWorkflowId(Number value) {
        setAttributeInternal(EPMWORKFLOWID, value);
    }
}
