package cux.oracle.apps.per.review.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WorkFlowInfoVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public WorkFlowInfoVOImpl() {
    }

    public void execWithClause(String groupName, String orgName, 
                               String phaseName, String period, 
                               String beginYear, String endYear, String status, 
                               String empName, Boolean query) {
        StringBuffer whereClause = new StringBuffer(500);
        whereClause.append(" 1 = 1 ");
        this.setWhereClause(null);

        if (groupName != null && !"".equals(groupName)) {
            whereClause.append(" AND GROUP_NAME = '" + groupName + "' ");
        }
        if (orgName != null && !"".equals(orgName)) {
            whereClause.append(" AND ORG_ID IN ");
            whereClause.append("       (SELECT E.ORGANIZATION_ID_CHILD ");
            whereClause.append("               FROM PER_ORG_STRUCTURE_ELEMENTS E ");
            whereClause.append("              WHERE E.ORG_STRUCTURE_VERSION_ID = CUX_JXKH_COMMON_PKG.GET_ORG_STRUCTURE_VERSION(CUX_JXKH_COMMON_PKG.GET_CONTRACT_EFFECTIVE_DATE(APPRAISAL_ID)) ");
            whereClause.append("             CONNECT BY E.ORGANIZATION_ID_PARENT = PRIOR ");
            whereClause.append("                        E.ORGANIZATION_ID_CHILD ");
            whereClause.append("                    AND E.ORG_STRUCTURE_VERSION_ID = CUX_JXKH_COMMON_PKG.GET_ORG_STRUCTURE_VERSION(CUX_JXKH_COMMON_PKG.GET_CONTRACT_EFFECTIVE_DATE(APPRAISAL_ID)) ");
            whereClause.append("              START WITH E.ORGANIZATION_ID_PARENT = (SELECT haou.organization_id FROM hr_all_organization_units haou WHERE haou.name = '" + 
                               orgName + "' ");
            whereClause.append("  AND ROWNUM = 1)  ");
            whereClause.append("                     AND E.ORG_STRUCTURE_VERSION_ID = CUX_JXKH_COMMON_PKG.GET_ORG_STRUCTURE_VERSION(CUX_JXKH_COMMON_PKG.GET_CONTRACT_EFFECTIVE_DATE(APPRAISAL_ID)) ");
            whereClause.append("             UNION ");
            whereClause.append(" SELECT haou.organization_id FROM hr_all_organization_units haou WHERE haou.name = '" + 
                               orgName + "' ");
            whereClause.append("  AND ROWNUM = 1) ");
        }
        if (phaseName != null && !"".equals(phaseName)) {
            whereClause.append(" AND PHASE_NAME = '" + phaseName + "' ");
        }
        if (period != null && !"".equals(period)) {
            whereClause.append(" AND PERIOD_NAME = '" + period + "' ");
        }
        if (beginYear != null && !"".equals(beginYear)) {
            whereClause.append(" AND APPRAISAL_YEAR >= " + beginYear + " ");
        }
        if (endYear != null && !"".equals(endYear)) {
            whereClause.append(" AND APPRAISAL_YEAR <= " + endYear + " ");
        }
        if (status != null && !"".equals(status)) {
            whereClause.append(" AND STATUS_NAME = '" + status + "' ");
        }
        if (empName != null && !"".equals(empName)) {
            whereClause.append(" AND EMP_NAME = '" + empName + "' ");
        }

        if (query != null && query.booleanValue()) {
            this.setWhereClause(whereClause.toString());
            this.executeQuery();
        }
    }
}
