package cux.oracle.apps.cux.qhse.rectify.poplist.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PaCiTypeListVORowImpl extends OAViewRowImpl {
    public static final int CITYPEID = 0;
    public static final int CINAME = 1;

    /**This is the default constructor (do not remove)
     */
    public PaCiTypeListVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute CiTypeId
     */
    public Number getCiTypeId() {
        return (Number)getAttributeInternal(CITYPEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CiTypeId
     */
    public void setCiTypeId(Number value) {
        setAttributeInternal(CITYPEID, value);
    }

    /**Gets the attribute value for the calculated attribute CiName
     */
    public String getCiName() {
        return (String)getAttributeInternal(CINAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CiName
     */
    public void setCiName(String value) {
        setAttributeInternal(CINAME, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CITYPEID:
            return getCiTypeId();
        case CINAME:
            return getCiName();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CITYPEID:
            setCiTypeId((Number)value);
            return;
        case CINAME:
            setCiName((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
