package cux.oracle.apps.cux.qhse.rectify.poplist.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProblemCategoryListVORowImpl extends OAViewRowImpl {
    public static final int CLASSCODEID = 0;
    public static final int CLASSCODE = 1;

    /**This is the default constructor (do not remove)
     */
    public ProblemCategoryListVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute ClassCodeId
     */
    public Number getClassCodeId() {
        return (Number)getAttributeInternal(CLASSCODEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ClassCodeId
     */
    public void setClassCodeId(Number value) {
        setAttributeInternal(CLASSCODEID, value);
    }

    /**Gets the attribute value for the calculated attribute ClassCode
     */
    public String getClassCode() {
        return (String)getAttributeInternal(CLASSCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ClassCode
     */
    public void setClassCode(String value) {
        setAttributeInternal(CLASSCODE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CLASSCODEID:
            return getClassCodeId();
        case CLASSCODE:
            return getClassCode();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CLASSCODEID:
            setClassCodeId((Number)value);
            return;
        case CLASSCODE:
            setClassCode((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
