package cux.oracle.apps.pa.project.server;

import oracle.apps.pa.project.server.AddProjectPartiesVOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CuxAddProjectPartiesVOImpl extends AddProjectPartiesVOImpl {
    /**This is the default constructor (do not remove)
     */
    public CuxAddProjectPartiesVOImpl() {
    }
}
