package cux.oracle.apps.pa.project.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RepSepcVORowImpl extends OAViewRowImpl {
    public static final int OBJECTID = 0;
    public static final int OBJECTTYPE = 1;
    public static final int RESOURCETYPEID = 2;
    public static final int RESOURCESOURCEID = 3;
    public static final int PROJECTROLEID = 4;
    public static final int STARTDATEACTIVE = 5;
    public static final int SPECIALTYCODE = 6;
    public static final int ATRRIBUTE1 = 7;
    public static final int ATRRIBUTE2 = 8;
    public static final int ATRRIBUTE3 = 9;
    public static final int ATRRIBUTE4 = 10;
    public static final int ATRRIBUTE5 = 11;
    public static final int ATRRIBUTE6 = 12;
    public static final int ATRRIBUTE7 = 13;
    public static final int ATRRIBUTE8 = 14;
    public static final int ATRRIBUTE9 = 15;
    public static final int CREATEDBY = 16;
    public static final int CREATIONDATE = 17;
    public static final int LASTUPDATEDBY = 18;
    public static final int LASTUPDATEDATE = 19;
    public static final int LASTUPDATELOGIN = 20;
    public static final int ROWID = 21;

    /**This is the default constructor (do not remove)
     */
    public RepSepcVORowImpl() {
    }

    /**Gets RepSepcEO entity object.
     */
    public RepSepcEOImpl getRepSepcEO() {
        return (RepSepcEOImpl)getEntity(0);
    }

    /**Gets the attribute value for OBJECT_ID using the alias name ObjectId
     */
    public Number getObjectId() {
        return (Number)getAttributeInternal(OBJECTID);
    }

    /**Sets <code>value</code> as attribute value for OBJECT_ID using the alias name ObjectId
     */
    public void setObjectId(Number value) {
        setAttributeInternal(OBJECTID, value);
    }

    /**Gets the attribute value for OBJECT_TYPE using the alias name ObjectType
     */
    public String getObjectType() {
        return (String)getAttributeInternal(OBJECTTYPE);
    }

    /**Sets <code>value</code> as attribute value for OBJECT_TYPE using the alias name ObjectType
     */
    public void setObjectType(String value) {
        setAttributeInternal(OBJECTTYPE, value);
    }

    /**Gets the attribute value for RESOURCE_TYPE_ID using the alias name ResourceTypeId
     */
    public Number getResourceTypeId() {
        return (Number)getAttributeInternal(RESOURCETYPEID);
    }

    /**Sets <code>value</code> as attribute value for RESOURCE_TYPE_ID using the alias name ResourceTypeId
     */
    public void setResourceTypeId(Number value) {
        setAttributeInternal(RESOURCETYPEID, value);
    }

    /**Gets the attribute value for RESOURCE_SOURCE_ID using the alias name ResourceSourceId
     */
    public Number getResourceSourceId() {
        return (Number)getAttributeInternal(RESOURCESOURCEID);
    }

    /**Sets <code>value</code> as attribute value for RESOURCE_SOURCE_ID using the alias name ResourceSourceId
     */
    public void setResourceSourceId(Number value) {
        setAttributeInternal(RESOURCESOURCEID, value);
    }

    /**Gets the attribute value for PROJECT_ROLE_ID using the alias name ProjectRoleId
     */
    public Number getProjectRoleId() {
        return (Number)getAttributeInternal(PROJECTROLEID);
    }

    /**Sets <code>value</code> as attribute value for PROJECT_ROLE_ID using the alias name ProjectRoleId
     */
    public void setProjectRoleId(Number value) {
        setAttributeInternal(PROJECTROLEID, value);
    }

    /**Gets the attribute value for START_DATE_ACTIVE using the alias name StartDateActive
     */
    public Date getStartDateActive() {
        return (Date)getAttributeInternal(STARTDATEACTIVE);
    }

    /**Sets <code>value</code> as attribute value for START_DATE_ACTIVE using the alias name StartDateActive
     */
    public void setStartDateActive(Date value) {
        setAttributeInternal(STARTDATEACTIVE, value);
    }

    /**Gets the attribute value for SPECIALTY_CODE using the alias name SpecialtyCode
     */
    public String getSpecialtyCode() {
        return (String)getAttributeInternal(SPECIALTYCODE);
    }

    /**Sets <code>value</code> as attribute value for SPECIALTY_CODE using the alias name SpecialtyCode
     */
    public void setSpecialtyCode(String value) {
        setAttributeInternal(SPECIALTYCODE, value);
    }

    /**Gets the attribute value for ATRRIBUTE1 using the alias name Atrribute1
     */
    public String getAtrribute1() {
        return (String)getAttributeInternal(ATRRIBUTE1);
    }

    /**Sets <code>value</code> as attribute value for ATRRIBUTE1 using the alias name Atrribute1
     */
    public void setAtrribute1(String value) {
        setAttributeInternal(ATRRIBUTE1, value);
    }

    /**Gets the attribute value for ATRRIBUTE2 using the alias name Atrribute2
     */
    public String getAtrribute2() {
        return (String)getAttributeInternal(ATRRIBUTE2);
    }

    /**Sets <code>value</code> as attribute value for ATRRIBUTE2 using the alias name Atrribute2
     */
    public void setAtrribute2(String value) {
        setAttributeInternal(ATRRIBUTE2, value);
    }

    /**Gets the attribute value for ATRRIBUTE3 using the alias name Atrribute3
     */
    public String getAtrribute3() {
        return (String)getAttributeInternal(ATRRIBUTE3);
    }

    /**Sets <code>value</code> as attribute value for ATRRIBUTE3 using the alias name Atrribute3
     */
    public void setAtrribute3(String value) {
        setAttributeInternal(ATRRIBUTE3, value);
    }

    /**Gets the attribute value for ATRRIBUTE4 using the alias name Atrribute4
     */
    public String getAtrribute4() {
        return (String)getAttributeInternal(ATRRIBUTE4);
    }

    /**Sets <code>value</code> as attribute value for ATRRIBUTE4 using the alias name Atrribute4
     */
    public void setAtrribute4(String value) {
        setAttributeInternal(ATRRIBUTE4, value);
    }

    /**Gets the attribute value for ATRRIBUTE5 using the alias name Atrribute5
     */
    public String getAtrribute5() {
        return (String)getAttributeInternal(ATRRIBUTE5);
    }

    /**Sets <code>value</code> as attribute value for ATRRIBUTE5 using the alias name Atrribute5
     */
    public void setAtrribute5(String value) {
        setAttributeInternal(ATRRIBUTE5, value);
    }

    /**Gets the attribute value for ATRRIBUTE6 using the alias name Atrribute6
     */
    public String getAtrribute6() {
        return (String)getAttributeInternal(ATRRIBUTE6);
    }

    /**Sets <code>value</code> as attribute value for ATRRIBUTE6 using the alias name Atrribute6
     */
    public void setAtrribute6(String value) {
        setAttributeInternal(ATRRIBUTE6, value);
    }

    /**Gets the attribute value for ATRRIBUTE7 using the alias name Atrribute7
     */
    public String getAtrribute7() {
        return (String)getAttributeInternal(ATRRIBUTE7);
    }

    /**Sets <code>value</code> as attribute value for ATRRIBUTE7 using the alias name Atrribute7
     */
    public void setAtrribute7(String value) {
        setAttributeInternal(ATRRIBUTE7, value);
    }

    /**Gets the attribute value for ATRRIBUTE8 using the alias name Atrribute8
     */
    public String getAtrribute8() {
        return (String)getAttributeInternal(ATRRIBUTE8);
    }

    /**Sets <code>value</code> as attribute value for ATRRIBUTE8 using the alias name Atrribute8
     */
    public void setAtrribute8(String value) {
        setAttributeInternal(ATRRIBUTE8, value);
    }

    /**Gets the attribute value for ATRRIBUTE9 using the alias name Atrribute9
     */
    public String getAtrribute9() {
        return (String)getAttributeInternal(ATRRIBUTE9);
    }

    /**Sets <code>value</code> as attribute value for ATRRIBUTE9 using the alias name Atrribute9
     */
    public void setAtrribute9(String value) {
        setAttributeInternal(ATRRIBUTE9, value);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for ROWID using the alias name RowID
     */
    public RowID getRowID() {
        return (RowID)getAttributeInternal(ROWID);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case OBJECTID:
            return getObjectId();
        case OBJECTTYPE:
            return getObjectType();
        case RESOURCETYPEID:
            return getResourceTypeId();
        case RESOURCESOURCEID:
            return getResourceSourceId();
        case PROJECTROLEID:
            return getProjectRoleId();
        case STARTDATEACTIVE:
            return getStartDateActive();
        case SPECIALTYCODE:
            return getSpecialtyCode();
        case ATRRIBUTE1:
            return getAtrribute1();
        case ATRRIBUTE2:
            return getAtrribute2();
        case ATRRIBUTE3:
            return getAtrribute3();
        case ATRRIBUTE4:
            return getAtrribute4();
        case ATRRIBUTE5:
            return getAtrribute5();
        case ATRRIBUTE6:
            return getAtrribute6();
        case ATRRIBUTE7:
            return getAtrribute7();
        case ATRRIBUTE8:
            return getAtrribute8();
        case ATRRIBUTE9:
            return getAtrribute9();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case ROWID:
            return getRowID();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case OBJECTID:
            setObjectId((Number)value);
            return;
        case OBJECTTYPE:
            setObjectType((String)value);
            return;
        case RESOURCETYPEID:
            setResourceTypeId((Number)value);
            return;
        case RESOURCESOURCEID:
            setResourceSourceId((Number)value);
            return;
        case PROJECTROLEID:
            setProjectRoleId((Number)value);
            return;
        case STARTDATEACTIVE:
            setStartDateActive((Date)value);
            return;
        case SPECIALTYCODE:
            setSpecialtyCode((String)value);
            return;
        case ATRRIBUTE1:
            setAtrribute1((String)value);
            return;
        case ATRRIBUTE2:
            setAtrribute2((String)value);
            return;
        case ATRRIBUTE3:
            setAtrribute3((String)value);
            return;
        case ATRRIBUTE4:
            setAtrribute4((String)value);
            return;
        case ATRRIBUTE5:
            setAtrribute5((String)value);
            return;
        case ATRRIBUTE6:
            setAtrribute6((String)value);
            return;
        case ATRRIBUTE7:
            setAtrribute7((String)value);
            return;
        case ATRRIBUTE8:
            setAtrribute8((String)value);
            return;
        case ATRRIBUTE9:
            setAtrribute9((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
