package cux.oracle.apps.pa.ds.lov.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DsLovAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public DsLovAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) { /* package name */
        /* Configuration Name */launchTester("cux.oracle.apps.pa.ds.lov.server", 
                                             "DsLovAMLocal");
    }

    /**Container's getter for DsProjectVO1
     */
    public DsProjectVOImpl getDsProjectVO1() {
        return (DsProjectVOImpl)findViewObject("DsProjectVO1");
    }

    /**Container's getter for TaskVO1
     */
    public TaskVOImpl getTaskVO1() {
        return (TaskVOImpl)findViewObject("TaskVO1");
    }

    /**Container's getter for SpecPersonVO1
     */
    public SpecPersonVOImpl getSpecPersonVO1() {
        return (SpecPersonVOImpl)findViewObject("SpecPersonVO1");
    }

    /**Container's getter for DsTemplateLovVO1
     */
    public DsTemplateLovVOImpl getDsTemplateLovVO1() {
        return (DsTemplateLovVOImpl)findViewObject("DsTemplateLovVO1");
    }

    /**Container's getter for DsSpecialityVO1
     */
    public DsSpecialityVOImpl getDsSpecialityVO1() {
        return (DsSpecialityVOImpl)findViewObject("DsSpecialityVO1");
    }
}
