package cux.oracle.apps.per.bonus.searchlist;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class searchVORowImpl extends OAViewRowImpl {
    public static final int PERSONDISTRIBUTIONID = 0;
    public static final int PERSONID = 1;
    public static final int LASTNAME = 2;
    public static final int ELEMENTNAME = 3;
    public static final int DISTRIBUTIONAMOUNT = 4;
    public static final int DISTRIBUTIONDEPNAME = 5;

    /**This is the default constructor (do not remove)
     */
    public searchVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute PersonDistributionId
     */
    public Number getPersonDistributionId() {
        return (Number)getAttributeInternal(PERSONDISTRIBUTIONID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PersonDistributionId
     */
    public void setPersonDistributionId(Number value) {
        setAttributeInternal(PERSONDISTRIBUTIONID, value);
    }

    /**Gets the attribute value for the calculated attribute PersonId
     */
    public Number getPersonId() {
        return (Number)getAttributeInternal(PERSONID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PersonId
     */
    public void setPersonId(Number value) {
        setAttributeInternal(PERSONID, value);
    }

    /**Gets the attribute value for the calculated attribute LastName
     */
    public String getLastName() {
        return (String)getAttributeInternal(LASTNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastName
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**Gets the attribute value for the calculated attribute ElementName
     */
    public String getElementName() {
        return (String)getAttributeInternal(ELEMENTNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ElementName
     */
    public void setElementName(String value) {
        setAttributeInternal(ELEMENTNAME, value);
    }

    /**Gets the attribute value for the calculated attribute DistributionAmount
     */
    public Number getDistributionAmount() {
        return (Number)getAttributeInternal(DISTRIBUTIONAMOUNT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DistributionAmount
     */
    public void setDistributionAmount(Number value) {
        setAttributeInternal(DISTRIBUTIONAMOUNT, value);
    }

    /**Gets the attribute value for the calculated attribute DistributiondepName
     */
    public String getDistributiondepName() {
        return (String)getAttributeInternal(DISTRIBUTIONDEPNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DistributiondepName
     */
    public void setDistributiondepName(String value) {
        setAttributeInternal(DISTRIBUTIONDEPNAME, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PERSONDISTRIBUTIONID:
            return getPersonDistributionId();
        case PERSONID:
            return getPersonId();
        case LASTNAME:
            return getLastName();
        case ELEMENTNAME:
            return getElementName();
        case DISTRIBUTIONAMOUNT:
            return getDistributionAmount();
        case DISTRIBUTIONDEPNAME:
            return getDistributiondepName();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PERSONDISTRIBUTIONID:
            setPersonDistributionId((Number)value);
            return;
        case PERSONID:
            setPersonId((Number)value);
            return;
        case LASTNAME:
            setLastName((String)value);
            return;
        case ELEMENTNAME:
            setElementName((String)value);
            return;
        case DISTRIBUTIONAMOUNT:
            setDistributionAmount((Number)value);
            return;
        case DISTRIBUTIONDEPNAME:
            setDistributiondepName((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
