package cux.oracle.apps.pa.docnum.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DocnumSummaryVORowImpl extends OAViewRowImpl {
    public static final int BATCHNUM = 0;
    public static final int PROJECTID = 1;
    public static final int SEGMENT1 = 2;
    public static final int NAME = 3;
    public static final int STATUS = 4;
    public static final int STATUSNAME = 5;
    public static final int DOCNAME = 6;
    public static final int REQDESC = 7;
    public static final int CREATEDBY = 8;
    public static final int CREATEDBYNAME = 9;
    public static final int CREATIONDATE = 10;
    public static final int APPROVERNAME = 11;

    /**This is the default constructor (do not remove)
     */
    public DocnumSummaryVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute BatchNum
     */
    public Number getBatchNum() {
        return (Number)getAttributeInternal(BATCHNUM);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BatchNum
     */
    public void setBatchNum(Number value) {
        setAttributeInternal(BATCHNUM, value);
    }

    /**Gets the attribute value for the calculated attribute ProjectId
     */
    public Number getProjectId() {
        return (Number)getAttributeInternal(PROJECTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProjectId
     */
    public void setProjectId(Number value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**Gets the attribute value for the calculated attribute Segment1
     */
    public String getSegment1() {
        return (String)getAttributeInternal(SEGMENT1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Segment1
     */
    public void setSegment1(String value) {
        setAttributeInternal(SEGMENT1, value);
    }

    /**Gets the attribute value for the calculated attribute Name
     */
    public String getName() {
        return (String)getAttributeInternal(NAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Name
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**Gets the attribute value for the calculated attribute Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**Gets the attribute value for the calculated attribute StatusName
     */
    public String getStatusName() {
        return (String)getAttributeInternal(STATUSNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StatusName
     */
    public void setStatusName(String value) {
        setAttributeInternal(STATUSNAME, value);
    }

    /**Gets the attribute value for the calculated attribute DocName
     */
    public String getDocName() {
        return (String)getAttributeInternal(DOCNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DocName
     */
    public void setDocName(String value) {
        setAttributeInternal(DOCNAME, value);
    }

    /**Gets the attribute value for the calculated attribute ReqDesc
     */
    public String getReqDesc() {
        return (String)getAttributeInternal(REQDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ReqDesc
     */
    public void setReqDesc(String value) {
        setAttributeInternal(REQDESC, value);
    }

    /**Gets the attribute value for the calculated attribute CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute CreatedByName
     */
    public String getCreatedByName() {
        return (String)getAttributeInternal(CREATEDBYNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreatedByName
     */
    public void setCreatedByName(String value) {
        setAttributeInternal(CREATEDBYNAME, value);
    }

    /**Gets the attribute value for the calculated attribute CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for the calculated attribute ApproverName
     */
    public String getApproverName() {
        return (String)getAttributeInternal(APPROVERNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ApproverName
     */
    public void setApproverName(String value) {
        setAttributeInternal(APPROVERNAME, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case BATCHNUM:
            return getBatchNum();
        case PROJECTID:
            return getProjectId();
        case SEGMENT1:
            return getSegment1();
        case NAME:
            return getName();
        case STATUS:
            return getStatus();
        case STATUSNAME:
            return getStatusName();
        case DOCNAME:
            return getDocName();
        case REQDESC:
            return getReqDesc();
        case CREATEDBY:
            return getCreatedBy();
        case CREATEDBYNAME:
            return getCreatedByName();
        case CREATIONDATE:
            return getCreationDate();
        case APPROVERNAME:
            return getApproverName();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case BATCHNUM:
            setBatchNum((Number)value);
            return;
        case PROJECTID:
            setProjectId((Number)value);
            return;
        case SEGMENT1:
            setSegment1((String)value);
            return;
        case NAME:
            setName((String)value);
            return;
        case STATUS:
            setStatus((String)value);
            return;
        case STATUSNAME:
            setStatusName((String)value);
            return;
        case DOCNAME:
            setDocName((String)value);
            return;
        case REQDESC:
            setReqDesc((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATEDBYNAME:
            setCreatedByName((String)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case APPROVERNAME:
            setApproverName((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
