package cux.oracle.apps.per.bonus.project.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---    财务部，采购部部长发放的明细列表（对某一次项目分配）
// ---------------------------------------------------------------------
public class DeptDistributionVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public DeptDistributionVOImpl() {
    }

    public void initQuery(int iPrjDistID) {
        setWhereClause(null);
        setWhereClauseParams(null);
        setWhereClauseParam(0, iPrjDistID);
        setMaxFetchSize(-1);
        executeQuery();
    }
}
