package cux.oracle.apps.cux.docinfo.lov.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CuxDocinfoDocTypeLovVORowImpl extends OAViewRowImpl {
    public static final int DOCUMENTTYPECODE = 0;
    public static final int DOCUMENTTYPENAME = 1;

    /**This is the default constructor (do not remove)
     */
    public CuxDocinfoDocTypeLovVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute DocumentTypeCode
     */
    public String getDocumentTypeCode() {
        return (String)getAttributeInternal(DOCUMENTTYPECODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DocumentTypeCode
     */
    public void setDocumentTypeCode(String value) {
        setAttributeInternal(DOCUMENTTYPECODE, value);
    }

    /**Gets the attribute value for the calculated attribute DocumentTypeName
     */
    public String getDocumentTypeName() {
        return (String)getAttributeInternal(DOCUMENTTYPENAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DocumentTypeName
     */
    public void setDocumentTypeName(String value) {
        setAttributeInternal(DOCUMENTTYPENAME, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case DOCUMENTTYPECODE:
            return getDocumentTypeCode();
        case DOCUMENTTYPENAME:
            return getDocumentTypeName();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case DOCUMENTTYPECODE:
            setDocumentTypeCode((String)value);
            return;
        case DOCUMENTTYPENAME:
            setDocumentTypeName((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
