package cux.oracle.apps.per.bonus.lov.server;

import cux.oracle.apps.per.bonus.advanceawards.server.AdvanceAwardsAMImpl;

import java.io.Reader;

import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Types;

import oracle.apps.fnd.framework.server.OADBTransaction;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpLovVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public EmpLovVOImpl() {
    }

    public void initQuery(int deptOrgID, int empOrgID, String distDate) {
        String strSQL = getQuerySQL(deptOrgID, empOrgID, distDate);
        setFullSqlMode(this.FULLSQL_MODE_AUGMENTATION);
        setWhereClause(null);
        cancelQuery();
        setQuery(strSQL);
        setMaxFetchSize(-1);
        executeQuery();
    }

    /* 获取查询SQL语句 */

    private String getQuerySQL(int deptOrgID, int empOrgID, String distDate) {
        EmployeeAMImpl amImpl = (EmployeeAMImpl)this.getApplicationModule();
        CallableStatement cs = null;
        OADBTransaction transaction = amImpl.getOADBTransaction();
        String strSQL = "";
        Clob cSQL = null;
        cs = 
 transaction.createCallableStatement("call CUX_HR_BONUS.GET_EmpLovVO_SQL(?, ?, ?, ?)", 
                                     1);
        try {
            cs.setInt(1, deptOrgID);
            cs.setInt(2, empOrgID);
            cs.setString(3, distDate);
            cs.registerOutParameter(4, Types.CLOB);
            cs.executeUpdate();
            cSQL = cs.getClob(4);
            Reader inStream = cSQL.getCharacterStream();
            char[] c = new char[(int)cSQL.length()];
            inStream.read(c);
            strSQL = new String(c);
            inStream.close();
            cs.close();
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        return strSQL;
    }
}
